# Limpieza de Memoria
```{r}
### Borro todos los objetos
  rm(list=ls())

### Garbage Collection
  gc()

# Importo Librerías
require("data.table")
require("rpart")
require("parallel")

# Seteo mis semillas
ksemillas  <- c(430007, 430487, 436757, 486947, 468697)
```

```{r}
# Particionamos el dataset
particionar  <- function( data,  division, agrupa="",  campo="fold", start=1, seed=NA )
{
  if(!is.na(seed))   set.seed(seed)

  bloque  <- unlist( mapply(  function(x,y) { rep( y, x )} ,   division,  seq( from=start, length.out=length(division) )  ) )  

  data[ , (campo) :=  sample( rep( bloque, ceiling(.N/length(bloque))) )[1:.N],
          by= agrupa ]
}

# CALCULO LA GANANCIA POR FOLD
ArbolEstimarGanancia  <- function( semilla, param_basicos )
{
  #particiono estratificadamente el dataset
  particionar( dataset, division=c(70,30), agrupa="clase_ternaria", seed= semilla )  #Cambiar por la primer semilla de cada uno !

  #genero el modelo
  modelo  <- rpart("clase_ternaria ~ .",     #quiero predecir clase_ternaria a partir del resto
                    data= dataset[fold==1],  #fold==1  es training,  el 70% de los datos
                    xval= 0,
                    control= param_basicos
                  )  #aqui van los parametros del arbol

  #aplico el modelo a los datos de testing
  prediccion  <- predict( modelo,   #el modelo que genere recien
                          dataset[fold==2],  #fold==2  es testing, el 30% de los datos
                          type= "prob") #type= "prob"  es que devuelva la probabilidad

  #calculo la ganancia en testing  qu es fold==2
  ganancia_test  <- dataset[ fold==2, 
                             sum( ifelse( prediccion[, "BAJA+2"]  >  1/60,
                                         ifelse( clase_ternaria=="BAJA+2", 59000, -1000 ),
                                         0 ) )]

  #escalo la ganancia como si fuera todo el dataset
  ganancia_test_normalizada  <-  ganancia_test / 0.3

  return( ganancia_test_normalizada )
}

# GENERO LOS PARAMETROS BASICOS PARA EL ARBOL
ArbolesMontecarlo  <- function( semillas,  param_basicos )
{
  ganancias  <- mcmapply( ArbolEstimarGanancia, 
                          semillas,   #paso el vector de semillas, que debe ser el primer parametro de la funcion ArbolEstimarGanancia
                          MoreArgs= list( param_basicos),  #aqui paso el segundo parametro
                          SIMPLIFY= FALSE,
                          mc.cores= 1 )  #se puede subir a 5 si posee Linux o Mac OS

  #media de las ganancias
  return(  unlist(ganancias) )
}
#------------------------------------------------------------------------------
```

```{r}
dataset  <- fread("./dataset/paquete_premium_202011.csv")

paramA  <- list( "cp"=         -1,  #complejidad minima
                 "minsplit"=  0,  #minima cantidad de registros en un nodo para hacer el split
                 "minbucket"= 500,  #minima cantidad de registros en una hoja
                 "maxdepth"=    10 ) #profundidad máxima del arbol


ganA <- ArbolesMontecarlo( ksemillas, paramA)

print(mean(ganA)/1000000)
```

```{r}

```