#Arbol elemental con libreria  rpart
#Debe tener instaladas las librerias  data.table  ,  rpart   y rpart.plot

```{r}
#cargo las librerias que necesito
require("data.table")
require("rpart")
require("rpart.plot")
```

```{r}
#Aqui se debe poner la carpeta de SU computadora local
setwd("A:/20. Formación Academica/02. Mineria de Datos/01. Cursos/08. Aplicaciones de Minería de Datos a Economía y Finanzas/MMD_Curso8_Labo")  #Establezco el Working Directory

#cargo los datos de 202011 que es donde voy a ENTRENAR el modelo
dtrain  <- fread("./dataset/paquete_premium_202011.csv")

#cargo los datos de 202011, que es donde voy a APLICAR el modelo
dapply  <- fread("./dataset/paquete_premium_202101.csv")
```

```{r}
#genero el modelo,  aqui se construye el arbol
modelo  <- rpart("clase_ternaria ~ .",  #quiero predecir clase_ternaria a partir de el resto de las variables
                 data = dtrain,
                 xval=0,
                 cp=        -0.3,   #esto significa no limitar la complejidad de los splits
                 minsplit= 8,     #minima cantidad de registros para que se haga el split
                 minbucket=  1,     #tamaño minimo de una hoja
                 maxdepth=   10 )    #profundidad maxima del arbol

#aplico el modelo a los datos nuevos
prediccion  <- predict( modelo, dapply , type = "prob")

#agrego a dapply una columna nueva que es la probabilidad de BAJA+2
dapply[ , prob_baja2 := prediccion[, "BAJA+2"] ]

#solo le envio estimulo a los registros con probabilidad de BAJA+2 mayor  a  1/60
dapply[ , Predicted  := as.numeric(prob_baja2 > 1/60) ]

#genero un dataset con las dos columnas que me interesan
entrega  <- dapply[   , list(numero_de_cliente, Predicted) ] #genero la salida

#genero el archivo para Kaggle
#creo la carpeta donde va el experimento
fwrite( entrega, 
        file= "./exp/KA2001/K101_001.csv", 
        sep= "," )
```


```{r}
#grafico el arbol
prp(modelo, extra=101, digits=5, branch=1, type=4, varlen=0, faclen=0)
```